# Generated by Django 5.1.7 on 2025-03-18 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('excerpt', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('public_access', models.CharField(choices=[('None', 'None'), ('Read Only', 'Read Only'), ('Read & Write', 'Read & Write')], default='Read Only', max_length=12)),
                ('authenticated_access', models.CharField(choices=[('None', 'None'), ('Read Only', 'Read Only'), ('Read & Write', 'Read & Write')], default='Read Only', max_length=12)),
                ('team_access', models.CharField(choices=[('None', 'None'), ('Read Only', 'Read Only'), ('Read & Write', 'Read & Write')], default='Read Only', max_length=12)),
                ('author_access', models.CharField(choices=[('None', 'None'), ('Read Only', 'Read Only'), ('Read & Write', 'Read & Write')], default='Read & Write', max_length=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
