# Generated by Django 5.1.7 on 2025-03-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_access',
            field=models.CharField(choices=[('Read Only', 'Read Only'), ('Read & Write', 'Read & Write')], default='Read & Write', max_length=12),
        ),
        migrations.AlterField(
            model_name='blog',
            name='public_access',
            field=models.CharField(choices=[('None', 'None'), ('Read Only', 'Read Only')], default='Read Only', max_length=12),
        ),
    ]
